# Churn Prediction Using Keras and Tf
Customer leaving the band and we have to preduct he customer who can leave bank in future

In [127]:
import pandas as pd
import tensorflow as tf


In [128]:
df=pd.read_csv('Churn_Modelling.csv')

In [129]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [130]:
df.shape

(10000, 14)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [132]:
churn=(df['Exited']==1).sum()

In [133]:
churn

np.int64(2037)

In [134]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [135]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [136]:
df["Gender"]=df['Gender'].map({'Female':0,'Male':1})

In [137]:
df = pd.get_dummies(df, columns=['Geography'], drop_first=True, dtype=int)


In [138]:
df.isnull().sum()

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_Germany    0
Geography_Spain      0
dtype: int64

In [139]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  Geography_Spain  
0               1        101348.88       1                  0                0  
1               1        112542.58       0                  0                1  
2               0        113931.57       1                  0                0  
3               0         93826.63       0                  0                0  
4               1         79084.10       0                  0                1

In [140]:
# scaling the values as some values are much ,more heigher than others

# Our Goal Is to Build Neral Network not Perfect model

In [141]:
from sklearn.preprocessing import StandardScaler

In [142]:
scaler=StandardScaler()

In [143]:
from sklearn.model_selection import train_test_split


In [144]:
X=df.drop(['Exited'],axis=1)
y=df['Exited']

In [145]:
X_train.shape

(8000, 11)

In [146]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [147]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [148]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.36766974,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ...,  1.6612541 ,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.25280688,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ..., -0.1427649 ,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ..., -0.05082558,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.81456811,
         1.72572313, -0.57638802]], shape=(8000, 11))

In [149]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense


In [150]:
model=Sequential()
# making layers
#1. Hidden_leayer with 3 neurons
model.add(Dense(3,activation='sigmoid',input_dim=11))
# “A Dense layer is a fully connected neural network layer where each neuron receives input from all neurons in the previous layer.”

#2.Output layer
model.add(Dense(1,activation='sigmoid'))




c:\Users\Dell\Desktop\DATA\tf_env\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [151]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [154]:
# model compilation
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [158]:
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4070
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.4070
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4069
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4069
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4068
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4068
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4067
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4067
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4066
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4066


In [159]:
# weight and biases values
model.layers[0].get_weights()

[array([[-0.15892595, -0.26310068,  0.16617246],
        [ 0.7810482 ,  0.14946502,  0.36698863],
        [ 0.03362613,  3.513785  , -2.5871608 ],
        [ 0.0179492 , -0.01678453,  0.08107664],
        [-0.4593843 , -0.28726602, -0.3300282 ],
        [ 0.24804032, -0.1805763 , -0.04088847],
        [-0.06190294,  0.121264  ,  0.0509506 ],
        [ 2.6324434 ,  1.2397127 , -0.67305684],
        [-0.29926765, -0.25569302,  0.10029068],
        [-1.0827706 , -0.1429714 , -0.5148501 ],
        [-0.18895078,  0.26611337,  0.1728565 ]], dtype=float32),
 array([ 0.4064911 , -0.38867652,  0.2191016 ], dtype=float32)]

In [164]:
# model [rediction with probabilities futher we have to set threshold and convert to 0 or 1]
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [165]:
#threshold
import numpy as np
y_pred=np.where(y_log>0.5,1,0)

In [166]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]], shape=(2000, 1))

In [167]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.841